# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "80:80"
#       - "8001:80"  # Vite (adjust as per your vite.config.js)
#     container_name: laravel_app
#     restart: unless-stopped
#     tty: true
#     environment:
#       SERVICE_NAME: laravel_app
#       SERVICE_TAGS: dev
#     working_dir: /var/www/html
#     volumes:
#       - ./:/var/www/html
#       - ./php.ini:/usr/local/etc/php/php.ini
#     networks:
#       - laravel

#   mysql:
#     image: mysql:8.0
#     container_name: laravel_mysql
#     restart: unless-stopped
#     tty: true
#     ports:
#       - "3306:3306"
#     environment:
#       MYSQL_DATABASE: laravel
#       MYSQL_USER: laravel
#       MYSQL_PASSWORD: secret
#       MYSQL_ROOT_PASSWORD: rootsecret
#     volumes:
#       - mysql_data:/var/lib/mysql
#     networks:
#       - laravel

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     platform: linux/amd64  # Add this line to force amd64
#     container_name: phpmyadmin
#     restart: unless-stopped
#     ports:
#       - "8081:80"  # Change this to an unused port
#     environment:
#       PMA_HOST: mysql
#       MYSQL_ROOT_PASSWORD: rootsecret
#     networks:
#       - laravel

# networks:
#   laravel:

# volumes:
#   mysql_data:
# version: '3.9'

# services:
#   app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     image: my-laravel-app
#     container_name: my-laravel-app
#     restart: unless-stopped
#     working_dir: /var/www/html
#     ports:
#       - "8000:80"
#     volumes:
#       - ./:/var/www/html
#       - ./.env:/var/www/html.env
#     environment:
#       - APP_ENV=local
#     networks:
#       - app-network
  
#   mysql:
#     platform: linux/x86_64 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
#     image: mysql:8.0
#     container_name: my-mysql
#     restart: unless-stopped
#     environment:
#       MYSQL_DATABASE: car_garage
#       MYSQL_USER: root
#       MYSQL_PASSWORD: rootsecret
#       MYSQL_ROOT_PASSWORD: rootsecret
#     volumes:
#       - dbdata:/var/lib/mysql
#     networks:
#       - app-network
#     ports:
#       - "3306:3306"

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin
#     platform: linux/amd64  # Add this line to force amd64
#     container_name: phpmyadmin
#     restart: unless-stopped
#     ports:
#       - "8081:80"  # Change this to an unused port
#     environment:
#       PMA_HOST: mysql
#       MYSQL_ROOT_PASSWORD: rootsecret
#     networks:
#       - app-network
  
#   vite:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "3002:3002"  # Mapea el puerto del contenedor al puerto del host
#     volumes:
#       - .:/var/www/html  # Monta el directorio actual en el contenedor para el desarrollo en vivo
#     command: ["npm", "run", "dev"]  # Comando para iniciar Vite
#     environment:
#       - NODE_ENV=development  # Establece el entorno de Node.js

  # nginx:
  #   image: nginx:alpine
  #   container_name: my-nginx
  #   ports:
  #     - "3001:80"
  #   volumes:
  #     - ./:/var/www
  #     - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   depends_on:
  #     - app
  #   networks:
  #     - app-network        

  # node:
  #   platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.node
  #   image: my-laravel-node
  #   container_name: my-laravel-node
  #   ports:
  #   - "3001:80"
  #   restart: unless-stopped
  #   working_dir: /var/www
  #   volumes:
  #     - ./:/var/www
  #     - /var/www/node_modules
  #   networks:
  #     - app-network


# networks:
#   app-network:
#     driver: bridge

# volumes:
#   dbdata:
#     driver: local

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - ./.env:/var/www/html.env
    environment:
      - APP_ENV=local
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network        

  node:
    platform: linux/arm64/v8 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    build:
      context: .
      dockerfile: Dockerfile.node
    image: my-laravel-node
    container_name: my-laravel-node
    ports:
    - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
      - /var/www/html/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - app-network

  db:
    platform: linux/x86_64 #this line is optional if you are using Mac Silicon chip (M1/M2/M3)
    image: mysql:8.0
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: car_garage
      MYSQL_USER: root
      MYSQL_PASSWORD: rootsecret
      MYSQL_ROOT_PASSWORD: rootsecret
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
    driver: local