
version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-laravel-app
    container_name: my-laravel-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
    - ${PWD}/:/var/www/html
    - ${PWD}/env:/var/www/html.env
    environment:
      - APP_ENV=local
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: my-nginx
    ports:
      - "8000:80"
    volumes:
    - ${PWD}/:/var/www/html
    - ${PWD}/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - app-network        

  node:
    build:
      context: .
      dockerfile: Dockerfile.node
    image: my-laravel-node
    container_name: my-laravel-node
    ports:
    - "3000:3000"
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
    - ${PWD}/:/var/www/html
    - /var/www/html/node_modules
    command: ["npm", "run", "dev"]
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: my-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: car_garage
      MYSQL_PASSWORD: rootsecret
      MYSQL_ROOT_PASSWORD: rootsecret
        #  volumes:
        # - dbdata:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

      #volumes:
      #  dbdata:
      # driver: local
